src/Deserializers/resources.php
src/Serializers/resources.php
src/resources.php
tests/Deserializers/resources.php
tests/Serializers/resources.php
tests/resources.php

The complexity of this regular expression is just not needed. Just search for the first occurrence of `/vendor/` or `/extensions/` and match everything from there, that's it. Using a regex character (`+`) as delimiter does have the advantage that it must not be repeated when calling `preg_quote`, it's always quoted.

Simplify remoteExtPath regex

---

composer.json
src/Deserializers/SnakDeserializer.js

Caused by https://github.com/wmde/DataValuesJavascript/pull/58.

Fix UnUnserializableValue rename

---

src/DeserializerFactory.js
src/Deserializers/Deserializer.js
src/SerializerFactory.js
src/Serializers/Serializer.js

These function names are not meant to be used, they make debugging easier because the debugger can then show the function name.

Add function names to JavaScript closures

---

resources.php
resources.tests.php
src/Deserializers/resources.php
src/Serializers/resources.php
src/resources.php
tests/Deserializers/resources.php
tests/Serializers/resources.php
tests/resources.php

I checked and no other set of resources files do this "not an entry point" check. This makes the files more similar to https://github.com/wikimedia/mediawiki-extensions-WikibaseJavaScriptApi/blob/master/resources.php and https://github.com/wikimedia/mediawiki-extensions-WikibaseJavaScriptApi/blob/master/resources.test.php.

Remove MEDIAWIKI dependency check

---

src/Deserializers/SnakDeserializer.js
tests/Deserializers/SnakDeserializer.tests.js

needs DataValues JavaScript 0.7.0 when we tag it

Handle UnDeserializableValue in SnakDeserializer

---

README.md
init.php

Note that this is **NOT** ready to be released because DataValues JavaScript 0.7.0 is not released yet!

Release 2.0.3

---

build/travis/script.sh

JSHint 2.9 is broken and should and can not be used. Our tests fail with this version.

Fix broken JSHint dependency

---

build/travis/script.sh
src/Deserializers/SnakListDeserializer.js

I want to see the number of warnings the bogus JSHint 2.9 creates in the report. We already fixed these warnings in most repositories. It may be worth the trouble to also update this repository, for consistency.
This reverts #25.

Revert downgrade to JSHint 2.8

---

README.md
composer.json
init.php

I double checked every detail in https://github.com/wmde/WikibaseDataModelJavascript and could not find a reason why this component should not be compatible with both versions.
This update is required to be able to update Wikibase.git to the new version of DataModel JavaScript.

Declare compatibility with DataModel JavaScript 2.0.0

---

README.md
composer.json
init.php

None of the changes in https://github.com/wmde/DataValuesJavascript/compare/0.7.0...0.8.0 is used in this component. So it's compatible with both versions.
This is needed for https://gerrit.wikimedia.org/r/263353.
[Bug: T117886](https://phabricator.wikimedia.org/T117886)

Release 2.0.6

---

README.md
composer.json
init.php

3.0.0 is not released yet, but I think this can be merged before this happens.

Declare compatibility with DataModel JavaScript 3.0

---

.gitignore
composer.json
phpcs.xml
resources.php
resources.tests.php
src/resources.php
tests/resources.php

This adds a PHPCS check for the first time, and fixes a few details already. Note that Travis currently doesn't run this new test. We need to change the way this code repository utilizes a `script.sh` shell script. This should be done in later patches.

Add PHPCS rule set and checks

---

.eslintrc.json
.gitignore
.travis.yml
build/travis/script.sh
package.json
tests/.eslintrc.json

Also removes the old-style build script and uses npm to run
the linter.
I'll add a change to run qunit tests as part of the CI build (without needing to install MediaWiki) separately.

Use eslint instead of jshint.

---

.travis.yml
README.md
composer.json
init.mw.php
init.php
mediawiki-extension.json
phpcs.xml
tests/SerializerFactory.tests.js

This patch is intended to do all the following things:
* Make Travis run PHPCS.
* Start using the extension.json format. Hooks and resource loader modules are missing, but it's a start.
* I'm also preparing a release here. But it does not contain anything relevant, so I suggest to *not* tag the actual release right now. We can do this any time later.

Start using extension.json and enable PHPCS on Travis

---

README.md
composer.json
src/Deserializers/SnakDeserializer.js
src/Serializers/SnakSerializer.js

`SnakSerializer` and `SnakDeserializer` gain support for serializing / deserializing the hash of a snak. (Serializing hashes is not required when sending serializations to the API, but the Wikibase view code assumes that serialization+deserialization is a lossless roundtrip, so if we don’t serialize it, the hash is lost when setting a new snak on a snakview.)

Add support for serialization of snak hashes

---

README.md
package.json

Needed for https://phabricator.wikimedia.org/T177613.
Note this includes commits from https://github.com/wmde/WikibaseSerializationJavaScript/pull/47 which should be merged first. The release-related commit is https://github.com/wmde/WikibaseSerializationJavaScript/commit/9ad2f022ede112a09154a82c1ba18c8c54015823.

Release 3.0.0

---

src/Deserializers/ClaimDeserializer.js
src/Deserializers/Deserializer.js
src/Deserializers/SnakDeserializer.js
src/Serializers/Serializer.js

I contacted Daniel Werner and asked him which email address he prefers.
I had two reasons to touch this:
* Daniels wikimedia.de email does not exist any more.
* He used so many different @author tags and I wanted to unify them.

Use Daniel Werners preferred email address

---

karma.conf.js
package.json

MediaWiki uses the CommonJS syntax to load packageFiles* through
resource loader. Since tests in this repo are not run via the usual
resource loader + qunit runner, we can use webpack to enable support for
CommonJS module syntax.

Add karma-webpack for `require` in tests/tested files

---

src/DeserializerFactory.js
src/Deserializers/StatementGroupDeserializer.js
src/Deserializers/StatementListDeserializer.js
tests/Deserializers/StatementListDeserializer.tests.js

wikibase.serialization.StatementListDeserializer is used in
WikibaseMediaInfo.
Bug: T233705
With this PR https://gerrit.wikimedia.org/r/c/mediawiki/extensions/Wikibase/+/538904 is actually green.

StatementListDeserializer: do not use require/module.exports

---

src/index.js

This was left out (mistakenly) when introducing index.js
Causing WikibaseLexeme to fail.
I double checked and nothing else is left out.

Add StatementGroupSetDeserializer to public interface

---

src/Deserializers/EntityDeserializer.js
src/Serializers/TermMapSerializer.js
src/index.js
tests/Deserializers/EntityDeserializer.tests.js
tests/Deserializers/ItemDeserializer.tests.js
tests/Deserializers/PropertyDeserializer.tests.js
tests/Serializers/TermMapSerializer.tests.js

These are not being used as global object anywhere anymore
Bug: T234993

Stop hooking to globals on EntityDeserializer and TermMapSerializer

---

karma.conf.js

Now that we're using proper modules, we need less file order gymnastics.
This can become even cleaner once it depends on the latest version of
wikibase.datamodel.

Clean up karma.conf.js

---

karma.conf.js
package.json

The test runner now does not need to load any datamodel files explicitly. They're all `require`d :)

Update datamodel to the version used in wikibase

---

.eslintrc.json
package.json
tests/Serializers/TermSerializer.tests.js

* had to upgrade eslint to make the plugin work, >= 4.0 seems to work but I see no reason to not just upgrade to 6
* fixed an "invalid" path in a test
The test folder could also be exempt from this rule because it doesn't matter there. Thoughts?

Lint package file require

---

.eslintrc.json
package.json

The `valid-package-file-require` rule got upstreamed to
eslint-plugin-mediawiki.

Use eslint-plugin-mediawiki
